FROM python:3.12-slim-bullseye

# Copiar el archivo requirements.txt
COPY requirements.txt .

# Instalar dependencias adicionales
RUN apt-get update && apt-get install -y python3-dev python3-dev gcc

# Actualizar numpy y scikit-learn
RUN pip install --upgrade numpy scikit-learn

# Actualizar numpy
RUN pip install --upgrade numpy

RUN pip install -r requirements.txt

RUN mkdir -p app

COPY ./App /app

WORKDIR app

EXPOSE 5000

RUN ls -la /app 

CMD [ "python3", "app.py"]